### ISSUE TITLE
flutter pub get - 502 Bad Gateway 

### ISSUE THREAD

**Issue by hw20101101** [ionicfirebaseapp/getwidget#222]
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^1.1.0
```

```
[example] flutter pub get
Running "flutter pub get" in example...                         
502 Bad Gateway trying to find package getwidget at https://pub.flutter-io.cn.

pub get failed (server unavailable) -- attempting retry 1 in 1 second...
```
